name: Android CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          OLIVIA_TEST: ${{ secrets.OLIVIA_TEST }}

      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Test Report 
