name: Android CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew :attentive-android-sdk:testDebugUnitTest --stacktrace --no-daemon
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Test Report 

  android-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [32]
        target: [google_apis]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew :attentive-android-sdk:connectedDebugAndroidTest --stacktrace
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
