name: Android CI

on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew :attentive-android-sdk:testDebugUnitTest --stacktrace --no-daemon
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Test Report 

  android-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [32]
        target: [google_apis]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3.3
          cache-read-only: false

      - name: Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          disk-size: 2G
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew :attentive-android-sdk:connectedDebugAndroidTest --stacktrace --no-daemon
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
